development:
  adapter: postgresql
  database: mtg_development
  host: localhost
  username: sudhirjonathan

test:
  adapter: postgresql
  database: mtg_test
  host: localhost
  username: sudhirjonathan
